name: Continuous Integration
on: 
  push:
    branches: 
      - 'main'

jobs:
  cache:
    name: "Warm up NPM cache"
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/version-check@v2
        id: check
        with:
          file-url: https://unpkg.com/@brakbricks/nest-brickset-api@latest/package.json
          static-checking: localIsNew
      - name: "Fail job when no change"
        if: steps.check.outputs.changed == 'false'
        run:
          exit 1
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      - run: npm ci
      - name: Upload node modules artifact
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules

  lint:
    needs: cache
    name: "Run linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Download node modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules    
      - run: npm run lint

  test:
    needs: cache
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Download node modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules    
      - run: npm run test

  build:
    needs:
        - 'lint'
        - 'test'
    name: "build module"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Download node modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules   
      - run: npm run build
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  
  create-github-release:
    needs: build
    name: "Create tag"
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and push tag
        uses: laputansoft/github-tag-action@v4.6
        with:
          default_bump: false
          github_token: ${{ env.github-token }}
          tag: v${{ steps.check-version.outputs.version }}
          release_branches: main



  
  