name: Continuous Integration
on: 
  push:
    branches: 
      - 'main'

jobs:
  check-version:
    uses: EndBug/version-check@v2
    with:
      file-url: https://unpkg.com/@brakbricks/nest-brickset-api@latest/package.json
      static-checking: localIsNew

  cache:
    if: steps.check-version.outputs.changed == 'true'
    name: "Warm up NPM cache"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      - run: npm ci

  lint:
    needs: cache
    name: "Run linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint

  test:
    needs: cache
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run test

  build:
    needs:
        - 'lint'
        - 'test'
    name: "build module"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
  
  create-github-release:
    needs: build
    name: "Create github release"
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and push tag
        uses: laputansoft/github-tag-action@v4.6
        with:
          default_bump: false
          github_token: ${{ env.github-token }}
          tag: v${{ steps.check-version.outputs.version }}
          release_branches: main
          


  
  