name: Create tag when version updates
on: 
  push:
    branches: 
      - 'main'

jobs:
  create-tag:
    name: "Create Tag"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EndBug/version-check@v2
        id: check
        with:
          file-url: https://unpkg.com/@brakbricks/nest-brickset-api@latest/package.json
          static-checking: localIsNew
      - name: Use Node.js
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      - run: npm ci  
        if: steps.check.outputs.changed == 'true'
      - run: npm run lint
        if: steps.check.outputs.changed == 'true'
      - run: npm run test 
        if: steps.check.outputs.changed == 'true'
      - name: Create Tag
        if: steps.check.outputs.changed == 'true'
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "v${{steps.check.outputs.version}}"



  
  